### ISSUE TITLE
Missing Loc for Designers 

### ISSUE THREAD

**Issue by egm-long** [Hermerico/avatar#36]
![image](https://user-images.githubusercontent.com/96354237/186462893-0f36954b-2db3-41b3-91e7-13dc6049c8c6.png)
![image](https://user-images.githubusercontent.com/96354237/186462942-96e4b967-fb54-4119-b9cd-9ba86d5e859e.png)
![image](https://user-images.githubusercontent.com/96354237/186462984-e3e9f077-0097-4be1-ab49-ee898af6e9ff.png)
![image](https://user-images.githubusercontent.com/96354237/186463029-e25778ae-9519-4111-a98f-b0727214bc89.png)
![image](https://user-images.githubusercontent.com/96354237/186463062-7a8814c9-e728-48c4-9223-87e7812df67e.png)

**Comment by creisimoserfacker** [comment]
fire designers have been adressed
